modLoader="javafml"
loaderVersion="[36,)"
license="Custom license"

[[mods]]
modId="elfworld"
version="1.0.0"
displayName="World of Elf"
credits="this mod is WIP"
displayURL="https://gamingforlife.eu"
logoFile="logo.png"
authors="eBrosTV"

[[dependencies.elfworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"


[[dependencies.elfworld]]
    modId="mcreator_link"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


